spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rental_db
    username: db_user
    password: db_password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

